name : Esteira de Validacao Java
on : 
 push: 
   branches: [ "main" ]

jobs: 
  compilar:
    runs-on: ubuntu-latest   

    steps:
    - name: Baixando o codigo no servidor  
      uses: actions/checkout@v4

    - name: Instalando o Java JDK no Servidor
      uses: actions/setup-java@v4
      whit:
        java-version: '17'
        distribution: 'temurin' 
    - name: Compilando Sistema 
      run: javac Validador.java

    - name: Executando Sistema
      run: java Validador       